In [3]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [4]:
# Load the MNIST dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [6]:
# Model Building
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.17168635,  0.7799854 ,  0.9792193 ,  0.52319455, -0.83823764,
         0.32211125,  0.8792699 ,  0.38000047,  0.37306666, -0.28807983]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.05519546, 0.14295821, 0.17447583, 0.11058246, 0.02834156,
        0.09043922, 0.15788025, 0.09582919, 0.09516703, 0.04913084]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.4030771

In [12]:
# Configure the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
# Train the model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


I0000 00:00:1748834315.199966   16143 service.cc:146] XLA service 0x73e7d8008450 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1748834315.199982   16143 service.cc:154]   StreamExecutor device (0): NVIDIA GeForce RTX 3060 Ti, Compute Capability 8.6
2025-06-02 11:18:35.217231: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2025-06-02 11:18:35.259589: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:531] Loaded cuDNN version 90101


 222/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.6802 - loss: 1.0699

I0000 00:00:1748834315.936261   16143 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8599 - loss: 0.4817
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 657us/step - accuracy: 0.9548 - loss: 0.1530
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 896us/step - accuracy: 0.9656 - loss: 0.1128
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - accuracy: 0.9741 - loss: 0.0860
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9759 - loss: 0.0791


In [14]:
# Evaluate the model
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9773 - loss: 0.0730


[0.07304585725069046, 0.9772999882698059]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.98105385e-07, 1.35292515e-08, 1.12331749e-04, 5.19578498e-05,
        1.32660835e-11, 4.35810705e-07, 4.64930074e-11, 9.99828577e-01,
        2.35734248e-07, 5.97904318e-06],
       [6.51247012e-09, 9.07392132e-06, 9.99976516e-01, 1.19049537e-05,
        1.46634077e-15, 2.44978924e-06, 6.57942534e-10, 1.02556462e-11,
        1.10588525e-08, 6.80079962e-13],
       [2.02231419e-07, 9.99503732e-01, 2.78369407e-05, 2.79702181e-06,
        1.55720390e-05, 1.57800496e-05, 1.26512296e-05, 3.28161230e-04,
        9.09064402e-05, 2.39626934e-06],
       [9.99443471e-01, 1.64302687e-08, 3.64507199e-04, 4.30903896e-07,
        1.91159302e-06, 1.11823356e-05, 1.00392361e-04, 3.40106708e-05,
        2.49942468e-06, 4.15427021e-05],
       [4.57474425e-06, 1.59188161e-07, 1.30367756e-04, 4.11042507e-08,
        9.98066127e-01, 7.03799287e-07, 1.80432507e-05, 1.19553944e-04,
        3.92942138e-06, 1.65656558e-03]], dtype=float32)>